### ISSUE TITLE
Deepstack Crash | The image processing stops working without any reason

### ISSUE THREAD

**Issue by CarpeDiemRo** [johnolafenwa/DeepStack#101]
**Environment**
1. RPI 4B, 8GB
2. NCS2
3. HA core-2021.3.4
4. robmarkcole/HASS-Deepstack-object Home Assistant add-on
5. HA installed in Docker, Deepstack installed in Docker
6. Six analogic cameras 1920x1080

**Automation**
1. Trigger when movement and /2 seconds during movement = true

**Actual results**
1. _Unknown_ status is displayed instead of the value. More precisely, the target value 0 is changed to _Unknown_ and remains like this.
![Screenshot 2021-04-28 at 15 39 36](https://user-images.githubusercontent.com/38489167/116405183-075b7000-a838-11eb-8434-3795f10ab9e0.png)
2. All the camera image_processing.xxx.yyy fails and shows _Unknown_ status

**What I tried**
1. Trigger manually all the cameras
2. No effect
3. sudo reboot -> the service is running again.

**Logs**
```
Logger: homeassistant.helpers.entity
Source: custom_components/deepstack_object/image_processing.py:350
First occurred: 12:40:22 PM (4781 occurrences)
Last logged: 3:31:45 PM

Update for image_processing.anna_persoane_camera_3 fails
Update for image_processing.anna_persoane_camera_5 fails
Update for image_processing.anna_persoane_camera_6 fails
Update for image_processing.anna_persoane_camera_1 fails
Update for image_processing.anna_persoane_camera_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 137, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 117, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 350, in process_image
    predictions = self._dsobject.detect(image)
  File "/usr/local/lib/python3.8/site-packages/deepstack/core.py", line 204, in detect
    return response["predictions"]
KeyError: 'predictions'
```

**OBS**
I am unable to reproduce manually and I didn't identify a root cause

**Comment by CarpeDiemRo** [comment]
The issue is not reproducible anymore, therefore it should be closed.
