### ISSUE TITLE
500 error processing custom models

### ISSUE THREAD

**Issue by pauloslfavc** [johnolafenwa/DeepStack#120]
I have been using the latest version of DeepStack: Version 2021.09.01 in 2 diferent systems: one is a ubuntu vm running on vmware ESXI, the other is a macbook pro m1. I am able to run detection of objects and faces without any issues.

Recently i tried to use some custom models from the samples, and for all of them i get a 500 from the server after 1 minute with this response body:
`{"success":false,"error":"failed to process request before timeout","duration":0}`

When the server starts i can see that the model was correctly detected:

`DeepStack: Version 2021.09.01
---------------------------------------
v1/vision/custom/licence-plate
---------------------------------------
v1/vision/custom/lplate
/v1/vision/face
---------------------------------------
/v1/vision/face/recognize
---------------------------------------
/v1/vision/face/register
---------------------------------------
/v1/vision/face/match
---------------------------------------
/v1/vision/face/list
---------------------------------------
/v1/vision/face/delete
---------------------------------------
/v1/vision/detection
---------------------------------------
/v1/vision/scene
---------------------------------------
---------------------------------------
v1/backup
---------------------------------------
v1/restore
`

Any idea how i can fix this issue?

**Comment by johnolafenwa** [comment]
Hello Paulo, thanks for reporting this.
Kindly post the error log after you observe this.
To obtain the error log, reproduce the error, then,

find the name of your container using ```docker ps```

run:
- ```sudo docker exec -it container_name /bin/bash```
Once you are in the container with the command above, run ```cd ../logs```
Then run ```nano stderr.txt``` to open the error logs, copy the contents and share it here.

This will give information about what went wrong and make it easier to fix

Thanks

**Comment by pauloslfavc** [comment]
Hi John ,
thanks a lot for your answer, here is the content of the stderr.txt:
root@19d5be7f510c:/app/logs# cat stderr.txt 
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/app/intelligencelayer/shared/detection.py", line 69, in objectdetection
    detector = YOLODetector(model_path, reso, cuda=CUDA_MODE)
  File "/app/intelligencelayer/shared/./process.py", line 36, in __init__
    self.model = attempt_load(model_path, map_location=self.device)
  File "/app/intelligencelayer/shared/./models/experimental.py", line 159, in attempt_load
    torch.load(w, map_location=map_location)["model"].float().fuse().eval()
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/app/intelligencelayer/shared/detection.py", line 69, in objectdetection
    detector = YOLODetector(model_path, reso, cuda=CUDA_MODE)
  File "/app/intelligencelayer/shared/./process.py", line 36, in __init__
    self.model = attempt_load(model_path, map_location=self.device)
  File "/app/intelligencelayer/shared/./models/experimental.py", line 159, in attempt_load
    torch.load(w, map_location=map_location)["model"].float().fuse().eval()
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.


This seems to be added at startup, as nothing is added here if i make a few requests, still i have always 500 on custom models :/

**Comment by johnolafenwa** [comment]
Hello @pauloslfavc , thanks for sharing the logs.
I tested the license plate model from the samples and it works well.
This error might be due to incomplete download of the model, or having downloaded the wrong file.

Kindly download this zip file https://github.com/odd86/deepstack_licenceplate_model/archive/refs/heads/main.zip, the model is contained in the models folder, you will need to pass the models folder to deepstack.  Run using the instructions here https://docs.deepstack.cc/custom-models/deployment/index.html

Do let me know if you encounter any errors.

**Comment by pauloslfavc** [comment]
Hi , you are absolutely right I seems a corrupted file, I downloaded it again and it works flawlessly:)
Thanks a lot for your support!
