### ISSUE TITLE
Errors in 2020.12.beta

### ISSUE THREAD

**Issue by balucanb** [johnolafenwa/DeepStack#69]
Not sure if this was already posted someplace else but just started getting the following in the stderr.txtx file, in AI-tool I am running the 2020.12 beta of deepstack. I am running CPU not GPU
Here is the error:

Process Process-1:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 297, in _bootstrap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 99, in run
  File "C:\DeepStack\intelligencelayer\shared\detection.py", line 138, in objectdetection
    os.remove(img_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\baluc\\AppData\\Local\\Temp\\DeepStack\\f28c9002-abb6-4e2e-a531-e7aa45b48e81'

**Comment by johnolafenwa** [comment]
Hello @balucanb , this error has been fixed in the latest update.
Please install the update CPU version here https://github.com/johnolafenwa/DeepStack/releases/download/0.2-beta/DeepStack-Installer-CPU.2021.01.beta.exe

And the updated GPU version here https://deepquest.sfo2.digitaloceanspaces.com/deepstack/DeepStack-Installer-GPU-Beta.2021.01.1.exe
