### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by balucanb** [johnolafenwa/DeepStack#71]
Getting the below error, running the newest beta of DS. Pulled this error from the stderr.txt in AI-Tool. I have uninstalled and reinstalled DS, running CPU not GPU. I am running 3 instances of DS, it will start up run for a short while then I get the error.

```
Process Process-1:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 297, in _bootstrap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 99, in run
  File "C:\DeepStack\intelligencelayer\shared\detection.py", line 138, in objectdetection
    os.remove(img_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\baluc\\AppData\\Local\\Temp\\DeepStack\\b6a0a2d5-5c7e-4347-afb4-0ca00b80e3d4'
```

**Comment by robmarkcole** [comment]
How you you running deepstack? Appears you need to `git lfs pull`

**Comment by balucanb** [comment]
I am running the latest windows beta version. This can actually be closed. I re-installed and it corrected the issue. Thanks
